jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip list  # Add this line to print installed packages for debugging

    - name: Debug information
      run: |
        ls -R  # Add this line to print directory structure for debugging
        env  # Add this line to print environment variables for debugging

    - name: Run tests
      run: pytest
